### ISSUE TITLE
valabind-cc doesn't exist on focal?

### ISSUE THREAD

**Issue by bannsec** [radare/valabind#56]
I'm attempting to r2pm install `r2api-python`, which is apparently requiring `valabind-cc`. However, that doesn't appear to exist on Ubuntu Focal:

```
dpkg -L valabind 
/.
/usr
/usr/bin
/usr/bin/valabind
/usr/share
/usr/share/doc
/usr/share/doc/valabind
/usr/share/doc/valabind/changelog.Debian.gz
/usr/share/doc/valabind/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/valabind
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/valabind.1.gz
```

**Comment by trufae** [comment]
Oh! after some investigations I find out Debian is now using MESON for packaging Valabind. and the meson.build had a bunch of issues:

* no project version specified (known meson issue)
* manpages not installed
* -cc script not installed

I did a new release (1.8.0) with this stuff fixed. will be good to tell Debian about this, so we can get a new package for Ubuntu. Can you handle this part? otherwise i guess mtainainers get warned when a new tag is pushed.

Thanks for reporting!
